target-version = "py312"

[lint]
select = [
    "A", # flake8-builtins
    "B", # flake8-bugbear"
    "C4", # flake8-comprehensions
    "C90", # mccabe
    "D",  # pydocstyle
    "E", "W", # pycodestyle
    "F", # pyflakes
    "I", # isort
    "N", # pep8-naming
    "PLC", "PLE", "PLW", # pylint
    "UP", # pyupgrade
    "YTT", # flake8-2020
]
ignore = [
    "D203",  # one-blank-line-before-class
    "D213",  # multi-line-summary-second-line
]
